### ISSUE TITLE
Making PatientListViewController.onPatientSelect() -> public

### ISSUE THREAD

**Issue by raheelsayeed** [smart-on-fhir/Swift-SMART#17]
Describing a use case: 

1. `Practitioner` logs in on a Tablet (SMART iOS App)
2. `Practitioner ` Selects `Patient`.
3. `Practitioner `/`Patient` do their thing .....
4. `Practitioner` writes new `FHIR` Resources to Server for that `Patient`.
5.  **`Practitioner` moves onto the next patient, requires selecting the patient from the list.**
6.  repeat steps

In the second last step, is `Practitioner` re-`authorization` **always** required to select a new patient? 

- if Yes: *simple way forward*
- if **NO**: I could use PatientListViewController instead of making my own. (`onPatientSelect()`) could be public. 

What do you think?

**Comment by p2** [comment]
In a user scope there’s no need to reauthorize. You can just query for all Patients again and show them in the patient list controller. This is what native patient select does, it doesn’t use the launch/patient scope and queries for all patients instead. 👍🏼

**Comment by raheelsayeed** [comment]
Are you saying I could use the builtin `PatientListViewController`? I can surely get all the patients listed in there, but:
`var onPatientSelect: ((Patient?) -> Void)?` callback isn't public, which kinda defeats the purpose of my usage, which is simply to select a patient.

**Comment by p2** [comment]
That's a good case to make it public, then! I'd recommend you use `PatientListViewController` however you see fit and submit a PR that makes the needed vars and methods public/open.
