### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by devjamie** [smart-on-fhir/Swift-SMART#2]
Any intentions on going to Swift 3?  If so, any ETA?

Thanks!

**Comment by p2** [comment]
Swift 3 is on the `feature/swift-3` and `feature/swift-3-dstu-2` branch. ;)

https://github.com/smart-on-fhir/Swift-SMART/tree/feature/swift-3

**Comment by devjamie** [comment]
OOooooo ok thank you!!  ~,<

**Comment by p2** [comment]
I'm in the process of merging into `develop` and `master`, so there might be changes in the next hours... ;)
