### ISSUE TITLE
'$' is not an identifier; use backticks to escape it

### ISSUE THREAD

**Issue by Fedenieto90** [smart-on-fhir/Swift-SMART#20]
When installing Swift-SMART 3.2.0 with cocoapods, the following error appears and the project does not build. The file is FHIROperation.swift, line 184:

/// Alias to `FHIROperation` for neat operation usage.
public typealias $ = FHIROperation

The message is the following: '$' is not an identifier; use backticks to escape it.

This does not happen when installing as embedded framework.

**Comment by Fedenieto90** [comment]
I could solve it. In Xcode I selected Pods targets, then SMART. Under the tab Build Settings I changed the Swift language version to 3.2. Maybe this can help others who came across the same problem. Now it works ok!

**Comment by andreasHausberger** [comment]
What xcode version are you using? I only can select 3.3 as a language version, and that doesn't solve it. Did you embed it via git clone or did you use a podfile?
