### ISSUE TITLE
Current Practitioner

### ISSUE THREAD

**Issue by Fedenieto90** [smart-on-fhir/Swift-SMART#22]
Hi, I'm working on a Practitioner facing app. I can log in as a practitioner and select a patient. I can get the information about the selected patient but I do not know how to access the current logged in Practitioner information. 

Is there a way to achieve this? 

Thanks!

**Comment by raheelsayeed** [comment]
This was recently pulled into the develop branch. (https://github.com/smart-on-fhir/Swift-SMART/pull/18) 
You'll have access to the `id_Token` through the `Client`, which you can use to resolve the user identity.

**Comment by Fedenieto90** [comment]
Thanks @raheelsayeed ! I am working on a previous version to support DSTU2. 

I've added the library in the podfile using the latest commit for version DSTU2 of the library:
`pod 'SMART', :git =>  'https://github.com/smart-on-fhir/Swift-SMART.git', :submodules => true, :commit => 'fddb9f11b89d5465f84b8ad5410be0c185637c8f'`

So I've done the same workaround by accessing that `id_Token` through the Client and then resolving the user identity.

Thanks.
