### ISSUE TITLE
Simulator will not work

### ISSUE THREAD

**Issue by DogandElk** [smart-on-fhir/Swift-SMART#24]
I downloaded the app and ran it in Xcode 9.3 with the build succeeding and without errors, however, no simulator appeared. I am brand new to SMART FHIR so I would appreciate any assistance you can offer.
Thanks !

**Comment by p2** [comment]
That’s because this repo is a framework, not an app, and it can’t be run by itself. See here for a sample app that uses this framework: https://github.com/smart-on-fhir/SoF-Demo

**Comment by DogandElk** [comment]
Thanks for forwarding.

I just downloaded the app, then created a podfile then added SMART to it. I received the following warning after the pod was installed :

Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] The `SoF-Demo [Debug]` target overrides the `OTHER_SWIFT_FLAGS` build setting defined in `Pods/Target Support Files/Pods-SoF-Demo/Pods-SoF-Demo.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `SoF-Demo [Release]` target overrides the `OTHER_SWIFT_FLAGS` build setting defined in `Pods/Target Support Files/Pods-SoF-Demo/Pods-SoF-Demo.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

I do not know what to do to correct this, can you help ?

I attempted to run the app and it failed with the following error despite the fact that I cleaned and rebuilt the app:

/Users/thomasglodekmd/Desktop/SoF-Demo-master/App/EndpointListViewController.swift:10:8: No such module 'SMART'




I would greatly appreciate your help.
Thanks !

Tom

**Comment by p2** [comment]
You don't need to add a Pod to the sample app, just follow the three steps listed in the README (and possibly fix problems related to the project's age) and you should be good to go.
