### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by Fedenieto90** [smart-on-fhir/Swift-SMART#25]
Hi, I'm working on a Practitioner facing app for iOS. The problem is that after 10 minutes, the requests start failing because of authentication. Is there a way to refresh the access token?

Thanks in advance!
Fede.

**Comment by p2** [comment]
You can call `smart.authorize()` again, which should use the refresh token if one is present. See [OAuth2's documentation](https://github.com/p2/OAuth2/tree/0c0d4a8d87cf9e7678fd2762b3e3ba1f18c5a5b0#8-re-authorize) for details.
