### ISSUE TITLE
Swift Compiler Error 

### ISSUE THREAD

**Issue by moomoogoo** [smart-on-fhir/Swift-SMART#4]
Hi when I try to build the current master, I keep getting a Swift Compiler Error: 

Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by p2** [comment]
I've just built Swift-SMART on master branch with Xcode 8.2 and it seems to work okay. What Xcode version are you using and what's the exact error?

**Comment by moomoogoo** [comment]
I'm using Xcode 8.2.1 and it seems to be missing the SwiftSMART/Swift-FHIR/Sources/ and SwiftSMART/OAuth2/ files after I download the master branch. Should the master branch be able to be complied right after downloading?

**Comment by p2** [comment]
Ah; that is part of the `OAuth2` submodule. It's better to use _git_ than to download the repo – the download does not contain all sources. Please see [here](https://github.com/smart-on-fhir/Swift-SMART/wiki/Installation).
