### ISSUE TITLE
Cannot authenticate with SMART FHIR sandbox server

### ISSUE THREAD

**Issue by gravicle** [smart-on-fhir/Swift-SMART#9]
*Disclaimer: I am very early in learning the FHIR stack, so please consider this issue with a noob in mind.*

When trying to authenticate with the Sandbox server, I am getting error:
```
CapabilityStatement.readFrom() did not return a CapabilityStatement instance but <Resource> https://fhir-api-dstu2.smarthealthit.org/
```
The SoF-Demo app (`master` and `develop`) is also running in to the same issue.

![simulator screen shot apr 7 2017 3 28 19 pm](https://cloud.githubusercontent.com/assets/1091114/24822021/fc9b8af0-1ba6-11e7-8ec8-df34f5a1f4c5.png)

What am I doing incorrectly? Is the issue that the SMART server is `dstu2` while the Swift SDK is targeting `stu3`?

**Comment by p2** [comment]
You're connecting to a DSTU-2 server with the STU-3 version of the framework.
